const electron = require('electron');

const { ipcRenderer: ipc } = electron;

const countdown = require('./countdown');
const video = require("./video");

function formatImgTag(doc, bytes) {
  const div = doc.createElement("div");
  div.classList.add("photo");
  const close = doc.createElement("div");
  close.classList.add("photoClose");
  const img = new Image();
  img.classList.add("photoImg");
  img.src = bytes;
  div.appendChild(img);
  div.appendChild(close);
  return div;
}

window.addEventListener("DOMContentLoaded", () => {
  const videoEl = document.getElementById("video");
  const canvasEl = document.getElementById("canvas");
  const recordEl = document.getElementById("record");
  const photoEl = document.getElementById("photo");
  const counterEl = document.getElementById("counter");

  const ctx = canvasEl.getContext("2d");

  // Init Of Video Stream
  video.init(navigator, videoEl);

  // To capture/ Record Image

  recordEl.addEventListener("click", () => {

    // To Add Count-Down To Record/Capture Image
    countdown.start(counterEl, 3, () => {
      const bytes = video.captureBytes(videoEl, ctx, canvasEl);

      // To Save Captured Image
      ipc.send('img-capture', bytes)
      //Image Tag for the generated Bytes
      photoEl.appendChild(formatImgTag(document, bytes));
    });
  });
});
